---
title: "Mel's Blog"
date: 2018-04-22
---
title: world leader
author: m3lsen
email: werwilldasschon@nurfuerspam.de
description: > # this means to ignore newlines until "baseurl:"
  Awesome description about how GitHub and I will be dominating the world and everything will be awesome af... wait for it!

# social links
twitter_username: not_available
github_username:  melleu

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
